name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Setiap hari jam 00:00 UTC
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats
        uses: anuraghazra/github-readme-stats@master
